## Homework 4

### Системы линейных уравнений

**1. Решить систему уравнений методом Гаусса:
$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$**

Запишем расширенную матрицу системы:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
2 & 1 & -1 & 1 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$$

Вычтем из строки 3 строку 1 и из строки 2 удвоенную строку 1.

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & 1 & 5 \\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$$

Оставшаяся матрица соответствует системе

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_4=0, \\
-x_{2}+x_{3}+5x_{4}=-2, \\
-2x_{3}+3x_{4}=4.
\end{cases}$$


Получаем бесконечное множество решений. Запишем решение в виде общего.

$$x_{4}=c,$$
$$-2x_{3}+3c=4 \; \Leftrightarrow \; x_{3}=1.5c - 2,$$
$$-x_{2} + 1.5c - 2 + 5c=-2 \; \Leftrightarrow \; x_{2}=6.5c,$$
$$x_{1} + 6.5c - 1.5c + 2 - 2c=0 \; \Leftrightarrow \; x_{1}=-3c - 2$$

**2. Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:**

**а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$**

По теореме Кронекера-Капелли: необходимым и достаточным условием совместности системы из $m$ уравнений с $n$ неизвестными является равенство между собой рангов матрицы коэффициентов $A$ и расширенной матрицы $\tilde A$

$$rank A=rank \tilde A.$$

Запишем расширенную матрицу системы:

$$\begin{pmatrix}
\left.\begin{matrix}
3 & -1 & 1 \\ 
2 & -5 & -3 \\ 
1 & 1 & -1
\end{matrix}\right|
\begin{matrix}
4\\ 
-17\\
0
\end{matrix}
\end{pmatrix}$$

In [15]:
# решим
import numpy as np
def check_matrix(a, b):
    a_rank = np.linalg.matrix_rank(a)
    b_rank = np.linalg.matrix_rank(b)
    n = len(a[0])
    if a_rank == b_rank == n:
        print(f'Ранг матрицы A = {a_rank}. Ранг расширенной матрицы = {b_rank}. n = {n}. '\
              'Система совместна и определена. Единственное решение')
    elif a_rank == b_rank and a_rank != n:
        print(f'Ранг матрицы A = {a_rank}. Ранг расширенной матрицы = {b_rank}. n = {n}. '\
              'Система совместна. Бесконечное множество решений')
    elif a_rank < b_rank:
        print(f'Ранг матрицы A = {a_rank}. Ранг расширенной матрицы = {b_rank}. n = {n}. '\
              'Система несовместна. Решений нет')        

In [16]:
a = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
a_ext = np.array([[3, -1, 1, 4], [2, -5, -3, -17], [1, 1, -1, 0]])
check_matrix(a, a_ext)

Ранг матрицы A = 3. Ранг расширенной матрицы = 3. n = 3. Система совместна и определена. Единственное решение


**б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$**

Запишем расширенную матрицу системы:

$$\begin{pmatrix}
\left.\begin{matrix}
2 & -4 & 6 \\ 
1 & -2 & 3 \\ 
3 & -6 & 9
\end{matrix}\right|
\begin{matrix}
1\\ 
-2\\
5
\end{matrix}
\end{pmatrix}$$

In [17]:
# решим
a = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
a_ext = np.array([[2, -4, 6, 1], [1, -2, 3, -2], [3, -6, 9, 5]])
check_matrix(a, a_ext)

Ранг матрицы A = 1. Ранг расширенной матрицы = 2. n = 3. Система несовместна. Решений нет


**в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$**

Запишем расширенную матрицу системы:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 5 \\ 
3 & 1 & -8
\end{matrix}\right|
\begin{matrix}
4\\ 
-2
\end{matrix}
\end{pmatrix}$$

In [18]:
# решим
a = np.array([[1, 2, 5], [3, 1, -8]])
a_ext = np.array([[1, 2, 5, 4], [3, 1, -8, -2]])
check_matrix(a, a_ext)

Ранг матрицы A = 2. Ранг расширенной матрицы = 2. n = 3. Система совместна. Бесконечное множество решений


**3. Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей
$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}$$**

In [19]:
# решим
a = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
a_ext = np.array([[1, 3, -2, 4, 3], [0, 5, 0, 1, 2], [0, 0, 3, 0, 4], [0, 0, 0, 2, 1]])
check_matrix(a, a_ext)

Ранг матрицы A = 4. Ранг расширенной матрицы = 4. n = 4. Система совместна и определена. Единственное решение


**4. Дана система линейных уравнений, заданная расширенной матрицей
$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}$$
Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.**

Из строки 2 вычтем строку 1, умноженную на 4, из строки 3 вычтем строку 1, умноженную на 7:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & -6 & -12
\end{matrix}\right|
\begin{matrix}
a\\ 
b - 4a\\
c - 7a
\end{matrix}
\end{pmatrix}$$

Из строки 3 вычтем удвоенную строку 2:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b - 4a\\
c + a - 2b
\end{matrix}
\end{pmatrix}$$

Система будет несовместна, если ранг A < ранга $\tilde A$. После преобразований можно заметить, что система будет несовместной при выполнения неравенства $c + a - 2b \neq 0$

### Часть 2

**1. Решить систему уравнений методом Крамера:**

**а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$**

In [52]:
# решим
a = np.array([[1, -2], [3, -4]])
b = np.array([1, 7])
a_x1 = np.array([[b[0], -2], [b[1], -4]])
a_x2 = np.array([[1, b[0]], [3, b[1]]])
print(f'x1: {np.linalg.det(a_x1)/np.linalg.det(a):.1f}, x2: {np.linalg.det(a_x2)/np.linalg.det(a):.1f}')
# check
np.linalg.solve(a, b)

x1: 5.0, x2: 2.0


array([5., 2.])

**б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$**

In [40]:
# решим
a = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
b = np.array([10, -2, 1])
a_x1 = np.array([[b[0], -1, 5], [b[1], 1, -3], [b[2], 4, 1]])
a_x2 = np.array([[2, b[0], 5], [1, b[1], -3], [2, b[2], 1]])
a_x3 = np.array([[2, -1, b[0]], [1, 1, b[1]], [2, 4, b[2]]])
print(f'x1:{np.linalg.det(a_x1)/np.linalg.det(a):.1f}, x2: {np.linalg.det(a_x2)/np.linalg.det(a):.1f}, '\
      f'x3: {np.linalg.det(a_x3)/np.linalg.det(a):.1f}')
# check
np.linalg.solve(a, b)

x1:2.0, x2: -1.0, x3: 1.0


array([ 2., -1.,  1.])

**2. Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:**

**а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$**

Домножим первую строку на 2 и вычтем ее из второй строки. Домножим первую строку на 3 и вычтем ее из третьей строки. Матрица коэффициентов:

$$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix}$$

L-матрица:

$$\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & l_{32} & 1
\end{pmatrix}$$

Умножим вторую строку на 4 и вычтем ее из третьей.

$$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix}$$

Итоговая L-матрица:

$$\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}$$

**б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$**

Домножим первую строку на 2 и вычтем ее из второй строки. Домножим первую строку на 3 и вычтем ее из третьей строки. Домножим первую строку на 4 и вычтем ее из четвертой строки. Матрица коэффициентов:

$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 15 & 23 & 6\\
0 & 18 & 45 & 17
\end{pmatrix}$$

L-матрица:

$$\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & l_{32} & 1 & 0\\
4 & l_{42} & l_{43} & 1
\end{pmatrix}$$

Домножим вторую строку на 5 и вычтем ее из третьей строки. Домножим вторую строку на 6 и вычтем ее из четвертой строки. Матрица коэффициентов:

$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 21 & 13
\end{pmatrix}$$

L-матрица:

$$\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0\\
4 & 6 & l_{43} & 1
\end{pmatrix}$$

Домножим третью строку на 7 и вычтем ее из четвертой строки. Матрица коэффициентов:

$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 0 & 6
\end{pmatrix}$$

Итоговая L-матрица:

$$\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0\\
4 & 6 & 7 & 1
\end{pmatrix}$$

**3. Решить систему линейных уравнений методом $LU$-разложения
$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$**

In [42]:
# решаем
from scipy.linalg import lu_factor, lu_solve
A = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
b = np.array([1, -6, -5])
lu, piv = lu_factor(A)
x = lu_solve((lu, piv), b)
print(f'x1 = {x[0]:.1f}, x2 = {x[1]:.1f}, x3 = {x[2]:.1f}')

x1 = -1.0, x2 = 0.0, x3 = 1.0


**4. Решить систему линейных уравнений методом Холецкого
$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$**

In [45]:
# решаем
from scipy.linalg import cho_factor, cho_solve
A = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
b = np.array([531, -460, 193])
c, low = cho_factor(A)
x = cho_solve((c, low), b)
print(f'x1 = {x[0]:.1f}, x2 = {x[1]:.1f}, x3 = {x[2]:.1f}')

x1 = 6.0, x2 = -5.0, x3 = -4.0


**5. Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.**

Реализуем метод Крамера

In [46]:
def det2(matrix):
    return matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]
 
def minor(matrix, i, j):
    tmp = [row for k, row in enumerate(matrix) if k != i]
    tmp = [col for k, col in enumerate(zip(*tmp)) if k != j]
    return tmp
 
def determinant(matrix):
    size = len(matrix)
    if size == 2:
        return det2(matrix)
 
    return sum((-1) ** j * matrix[0][j] * determinant(minor(matrix, 0, j))
               for j in range(size))

In [69]:
def kramer(a, b):
    det = determinant(a)
    det_list = []
    mod_a = []
    mod_line = []
    for i in range(len(a)):
        for idx, line in enumerate(a):
            mod_line = line.copy()
            mod_line[i] = b[idx]
            mod_a.append(mod_line)
            mod_line = []
        det_list.append(determinant(mod_a))
        mod_a = []
    for i in range(len(det_list)):
        print(f'Корень x{i+1} = {det_list[i]/det}')

In [70]:
# решаем
a = [[1, -2], [3, -4]]
b = [1, 7]
kramer(a, b)

Корень x1 = 5.0
Корень x2 = 2.0


In [71]:
# проверяем
np.linalg.solve(a, b)

array([5., 2.])

In [72]:
# решаем
a = [[2, -1, 5], [1, 1, -3], [2, 4, 1]]
b = [10, -2, 1]
kramer(a, b)

Корень x1 = 2.0
Корень x2 = -1.0
Корень x3 = 1.0


In [73]:
# проверяем
np.linalg.solve(a, b)

array([ 2., -1.,  1.])