## Homework 2

### Матрицы и матричные операции

**1. Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:**

**а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;**

Для того, чтобы произведения матриц были определены, их размерности должны быть $m\times n$ и $n\times k$ (чтобы число столбцов матрицы $A$ было равно числу строк матрицы $B$). Таким образом, произведения матриц AB и BA не определены.

**б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;**

Из описанного выше условия, произведение матриц AB определено, размерность полученной матрицы $2 \times 3$. Произведение матриц BA не определено.

**в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;**

Из описанного выше условия, произведение матриц AB определено, размерность полученной матрицы $8 \times 8$. Произведение матриц BA определено, размерность полученной матрицы $3 \times 3$.

**г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.**

Из описанного выше условия, произведение матриц AB и BA определены, размерность полученных матриц $4 \times 4$.

**2. Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$**

Сумма матриц:

$$A + B = 
\begin{pmatrix}
1 & -2\\ 
3 & 0\\
\end{pmatrix} + \begin{pmatrix}
4 & -1\\ 
0 & 5\\  
\end{pmatrix} = \begin{pmatrix}
5 & -3\\ 
3 & 5\\ 
\end{pmatrix}$$

Произведение матриц $A\cdot B$:

$$A\cdot B=\begin{pmatrix}
1\cdot4-2\cdot0 & 1\cdot(-1)-2\cdot5\\ 
3\cdot4+0\cdot0 & 3\cdot(-1)+0\cdot5\\ 
\end{pmatrix}=\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}.$$

Произведение матриц $B\cdot A$:

$$B\cdot A=\begin{pmatrix}
4\cdot1-1\cdot3 & 4\cdot(-2)-1\cdot0\\ 
0\cdot1+5\cdot3 & 0\cdot(-2)+5\cdot0\\ 
\end{pmatrix}=\begin{pmatrix}
1 & -8\\ 
15 & 0
\end{pmatrix}.$$

In [1]:
# проверяем
import numpy as np
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица A+B\n{A + B}')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

Матрица A
[[ 1 -2]
 [ 3  0]]
Матрица B
[[ 4 -1]
 [ 0  5]]
Матрица A+B
[[ 5 -3]
 [ 3  5]]
Матрица AB
[[  4 -11]
 [ 12  -3]]
Матрица BA
[[ 1 -8]
 [15  0]]


**3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$**

$3A=\begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix}$, $2B=\begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix}$, $4C=\begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix}.$

$$3A - 2B + 4C = 
\begin{pmatrix}
3 - 0 + 8 & 21 - 10 - 16\\ 
9 - 4 + 4 & -18 + 2 + 4\\
\end{pmatrix} = \begin{pmatrix}
11 & -5\\ 
9 & -12\\ 
\end{pmatrix}$$

In [2]:
# проверяем
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица C\n{C}')
print(f'Матрица 3A-2B+4C\n{3 * A - 2 * B + 4 * C}')

Матрица A
[[ 1  7]
 [ 3 -6]]
Матрица B
[[ 0  5]
 [ 2 -1]]
Матрица C
[[ 2 -4]
 [ 1  1]]
Матрица 3A-2B+4C
[[ 11  -5]
 [  9 -12]]


**4. Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.**

$A^T=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}$.

$$A\cdot A^T=\begin{pmatrix}
4\cdot4+1\cdot1 & 4\cdot5+1\cdot(-2)& 4\cdot2+1\cdot3\\ 
5\cdot4-2\cdot1 & 5\cdot5-2\cdot(-2)& 5\cdot2-2\cdot3\\
2\cdot4+3\cdot1 & 2\cdot5+3\cdot(-2)& 2\cdot2+3\cdot3\\
\end{pmatrix}=\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\
11 & 4 & 13\\
\end{pmatrix}.$$

$$A^T\cdot A=\begin{pmatrix}
4\cdot4+5\cdot5+2\cdot2 & 4\cdot1+5\cdot(-2)+2\cdot3\\ 
1\cdot4-2\cdot5+3\cdot2 & 1\cdot1-2\cdot(-2)+3\cdot3
\end{pmatrix}=\begin{pmatrix}
45 & 0\\ 
0 & 14
\end{pmatrix}.$$

In [3]:
# проверяем
A = np.array([[4, 1], [5, -2], [2, 3]])

print(f'Матрица A\n{A}')
print(f'Матрица A_T\n{A.T}')
print(f'Матрица AA_T\n{np.dot(A, A.T)}')
print(f'Матрица A_TA\n{np.dot(A.T, A)}')

Матрица A
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
Матрица A_T
[[ 4  5  2]
 [ 1 -2  3]]
Матрица AA_T
[[17 18 11]
 [18 29  4]
 [11  4 13]]
Матрица A_TA
[[45  0]
 [ 0 14]]


**5. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.**

In [16]:
def check_matrix(a):
    matrix_lines = len(a)
    matrix_columns = 0
    for line in a:
        if matrix_columns == 0:
            matrix_columns = len(line)
        elif len(line) != matrix_columns:
            raise ValueError('Incorrect matrix')
    return matrix_lines, matrix_columns

def matrix_prod(a, b):
    result = []
    line_list = []
    el_sum = 0
    matrix_a_lines, matrix_a_columns = check_matrix(a)
    matrix_b_lines, matrix_b_columns = check_matrix(b)
    if matrix_a_columns != matrix_b_lines:
        raise ValueError('Incorrect matrix size')
    else:
        for line_idx in range(matrix_a_lines):
            for column_b_idx in range(matrix_b_columns):
                for idx in range(matrix_a_columns):
                    el_sum += a[line_idx][idx] * b[idx][column_b_idx]
                line_list.append(el_sum)
                el_sum = 0
            result.append(line_list)
            line_list = []
    return result

In [17]:
# проверяем
a = [[1, 2, 4], [3, 4, 6]]
b = [[1, 2], [3, 2], [7, 2]]
print(matrix_prod(a, b))
A = np.array(a)
B = np.array(b)
print(A.dot(B))

[[35, 14], [57, 26]]
[[35 14]
 [57 26]]


### Часть 2

**1.Вычислить определитель:**

**a)
$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix} = sin^2x + cos^2x = 1$$**

**б)
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix} = 4 \cdot 5 \cdot 9 = 180$$**

In [18]:
# проверяем
a = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[4 2 3]
 [0 5 1]
 [0 0 9]]
Определитель:
180


**в)
$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = 
\begin{vmatrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & -6 & -12
\end{vmatrix} = 
\begin{vmatrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & 0 & 0
\end{vmatrix} = 0$$**

Мы умножили первую строку на 4 и 7 и вычли результат из строк 2 и 3 соответственно, потом вычли удвоенную строку 2 из строки 3. В результате у матрицы появилась нулевая строка, из чего следует, что определитель равен нулю, а исходная матрица - вырожденная.

In [19]:
# проверяем
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
-0


**2. Определитель матрицы $A$ равен $4$. Найти:**

**а) $det(A^{2})$**

Из свойств определителя, $$det(AA)=detA\cdot detA = 16$$

**б) $det(A^{T})$**

Из свойств определителя, определитель транспонированной матрицы равен определителю исходной = 4.

**в) $det(2A)$**

Из свойства определителя "умножение строки или столбца матрицы на число $\lambda$ приведет к умножению определителя матрицы на то же число" следует, что $det(2A) = 4\cdot2^n$, где n - количество строк матрицы. 

**3. Доказать, что матрица
$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
вырожденная.**

Матрица является вырожденной, если ее определитель равен нулю. Из свойств определителя известно, что если две строки матрицы линейно зависимы, то определитель этой матрицы равен нулю. Замечаем, что строки 1 и 2 линейно зависимы (строка 2 равна удвоенной строке 1 с измененным знаком), таким образом исследуемая матрица - вырожденная.

**4. Найти ранг матрицы:**

**а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix}$**

Замечаем, что строка 3 является линейной комбинацией строк 1 и 2, исключаем ее, вычитаем из строки 2 строку 1:

$$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1
\end{pmatrix} = 
\begin{pmatrix}
1 & 2 & 3\\ 
0 & -1 & -2
\end{pmatrix}$$

Ранг матрицы = 2.

In [26]:
# проверяем
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
print(f'Матрица:\n{a}')
print(f'Ранг матрицы:\n{np.linalg.matrix_rank(a)}')

Матрица:
[[1 2 3]
 [1 1 1]
 [2 3 4]]
Ранг матрицы:
2


**б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}$**

Строка 3 является линейной комбинацией строк 1 и 2, исключаем ее, вычитаем из строки 1 строку 2 и меняем столбцы местами:

$$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
2 & 3 & 5 & 6
\end{pmatrix} =
\begin{pmatrix}
0 & 0 & 0 & -1\\ 
0 & 0 & 2 & 2\\ 
2 & 3 & 5 & 6
\end{pmatrix} = 
\begin{pmatrix}
-1 & 0 & 0 & 0\\ 
2 & 2 & 0 & 0\\ 
6 & 5 & 3 & 2
\end{pmatrix}$$

Ранг матрицы = 3

In [27]:
# проверяем
a = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
print(f'Матрица:\n{a}')
print(f'Ранг матрицы:\n{np.linalg.matrix_rank(a)}')

Матрица:
[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]
Ранг матрицы:
3
